# site settings
title: Michael Kaufman
subtitle: Web Developer
email: mkaufman94@gmail.com
description: I'm a web developer based in Knoxville, TN looking to move to Nashville for family
baseurl: # the subpath of your site, e.g. /blog
url: "https://thebluepotion.com" # the base hostname & protocol for your site
author: Michael Kaufman
street_address: 2720 Avalon Bay Rd
city: Maryville
state: TN
zip_code: 37804
country: United States of America
phone: (865) 363 - 4725

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/maksusername
github_url: https://github.com/MakMcFly
linkedin_url: https://www.linkedin.com/in/michael-kaufman-0911939a/

# build settings
markdown: kramdown

sass:
  style: compressed
